export const countryData = [
  { name: "Afghanistan", dialCode: "+93", code: "AF", maxLength: 9, flag: "🇦🇫" },
  { name: "Albania", dialCode: "+355", code: "AL", maxLength: 9, flag: "🇦🇱" },
  { name: "Algeria", dialCode: "+213", code: "DZ", maxLength: 9, flag: "🇩🇿" },
  { name: "Andorra", dialCode: "+376", code: "AD", maxLength: 6, flag: "🇦🇩" },
  { name: "Argentina", dialCode: "+54", code: "AR", maxLength: 10, flag: "🇦🇷" },
  { name: "Australia", dialCode: "+61", code: "AU", maxLength: 9, flag: "🇦🇺" },
  { name: "Austria", dialCode: "+43", code: "AT", maxLength: 10, flag: "🇦🇹" },
  { name: "Bangladesh", dialCode: "+880", code: "BD", maxLength: 10, flag: "🇧🇩" },
  { name: "Belgium", dialCode: "+32", code: "BE", maxLength: 9, flag: "🇧🇪" },
  { name: "Brazil", dialCode: "+55", code: "BR", maxLength: 11, flag: "🇧🇷" },
  { name: "Canada", dialCode: "+1", code: "CA", maxLength: 10, flag: "🇨🇦" },
  { name: "China", dialCode: "+86", code: "CN", maxLength: 11, flag: "🇨🇳" },
  { name: "Colombia", dialCode: "+57", code: "CO", maxLength: 10, flag: "🇨🇴" },
  { name: "Denmark", dialCode: "+45", code: "DK", maxLength: 8, flag: "🇩🇰" },
  { name: "Egypt", dialCode: "+20", code: "EG", maxLength: 10, flag: "🇪🇬" },
  { name: "Finland", dialCode: "+358", code: "FI", maxLength: 10, flag: "🇫🇮" },
  { name: "France", dialCode: "+33", code: "FR", maxLength: 9, flag: "🇫🇷" },
  { name: "Germany", dialCode: "+49", code: "DE", maxLength: 11, flag: "🇩🇪" },
  { name: "Greece", dialCode: "+30", code: "GR", maxLength: 10, flag: "🇬🇷" },
  { name: "India", dialCode: "+91", code: "IN", maxLength: 10, flag: "🇮🇳" },
  { name: "Indonesia", dialCode: "+62", code: "ID", maxLength: 11, flag: "🇮🇩" },
  { name: "Iran", dialCode: "+98", code: "IR", maxLength: 10, flag: "🇮🇷" },
  { name: "Iraq", dialCode: "+964", code: "IQ", maxLength: 10, flag: "🇮🇶" },
  { name: "Ireland", dialCode: "+353", code: "IE", maxLength: 9, flag: "🇮🇪" },
  { name: "Israel", dialCode: "+972", code: "IL", maxLength: 9, flag: "🇮🇱" },
  { name: "Italy", dialCode: "+39", code: "IT", maxLength: 10, flag: "🇮🇹" },
  { name: "Japan", dialCode: "+81", code: "JP", maxLength: 10, flag: "🇯🇵" },
  { name: "Kenya", dialCode: "+254", code: "KE", maxLength: 9, flag: "🇰🇪" },
  { name: "Malaysia", dialCode: "+60", code: "MY", maxLength: 9, flag: "🇲🇾" },
  { name: "Mexico", dialCode: "+52", code: "MX", maxLength: 10, flag: "🇲🇽" },
  { name: "Morocco", dialCode: "+212", code: "MA", maxLength: 9, flag: "🇲🇦" },
  { name: "Nepal", dialCode: "+977", code: "NP", maxLength: 10, flag: "🇳🇵" },
  { name: "Netherlands", dialCode: "+31", code: "NL", maxLength: 9, flag: "🇳🇱" },
  { name: "New Zealand", dialCode: "+64", code: "NZ", maxLength: 9, flag: "🇳🇿" },
  { name: "Nigeria", dialCode: "+234", code: "NG", maxLength: 10, flag: "🇳🇬" },
  { name: "Norway", dialCode: "+47", code: "NO", maxLength: 8, flag: "🇳🇴" },
  { name: "Pakistan", dialCode: "+92", code: "PK", maxLength: 10, flag: "🇵🇰" },
  { name: "Philippines", dialCode: "+63", code: "PH", maxLength: 10, flag: "🇵🇭" },
  { name: "Poland", dialCode: "+48", code: "PL", maxLength: 9, flag: "🇵🇱" },
  { name: "Portugal", dialCode: "+351", code: "PT", maxLength: 9, flag: "🇵🇹" },
  { name: "Russia", dialCode: "+7", code: "RU", maxLength: 10, flag: "🇷🇺" },
  { name: "Saudi Arabia", dialCode: "+966", code: "SA", maxLength: 9, flag: "🇸🇦" },
  { name: "Singapore", dialCode: "+65", code: "SG", maxLength: 8, flag: "🇸🇬" },
  { name: "South Africa", dialCode: "+27", code: "ZA", maxLength: 9, flag: "🇿🇦" },
  { name: "South Korea", dialCode: "+82", code: "KR", maxLength: 10, flag: "🇰🇷" },
  { name: "Spain", dialCode: "+34", code: "ES", maxLength: 9, flag: "🇪🇸" },
  { name: "Sri Lanka", dialCode: "+94", code: "LK", maxLength: 9, flag: "🇱🇰" },
  { name: "Sweden", dialCode: "+46", code: "SE", maxLength: 9, flag: "🇸🇪" },
  { name: "Switzerland", dialCode: "+41", code: "CH", maxLength: 9, flag: "🇨🇭" },
  { name: "Thailand", dialCode: "+66", code: "TH", maxLength: 9, flag: "🇹🇭" },
  { name: "Turkey", dialCode: "+90", code: "TR", maxLength: 10, flag: "🇹🇷" },
  { name: "Ukraine", dialCode: "+380", code: "UA", maxLength: 9, flag: "🇺🇦" },
  { name: "United Arab Emirates", dialCode: "+971", code: "AE", maxLength: 9, flag: "🇦🇪" },
  { name: "United Kingdom", dialCode: "+44", code: "GB", maxLength: 10, flag: "🇬🇧" },
  { name: "United States", dialCode: "+1", code: "US", maxLength: 10, flag: "🇺🇸" },
  { name: "Vietnam", dialCode: "+84", code: "VN", maxLength: 10, flag: "🇻🇳" }
];
